settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  domain: "machine_learning"
  links:
    - https://arxiv.org/pdf/2208.07339
    - https://arxiv.org/pdf/2311.09476
